-- Create payment transactions table to track all PayU payments
CREATE TABLE IF NOT EXISTS payment_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employer_id UUID NOT NULL REFERENCES employers(id) ON DELETE CASCADE,
  
  -- Plan details
  plan_type VARCHAR(50) NOT NULL CHECK (plan_type IN ('free', 'classic', 'premium')),
  billing_cycle VARCHAR(20) CHECK (billing_cycle IN ('monthly', 'annual')),
  amount INTEGER NOT NULL, -- Amount in paise (INR * 100)
  
  -- Payment gateway details
  payment_gateway VARCHAR(50) DEFAULT 'payu',
  transaction_id VARCHAR(255), -- PayU transaction ID
  payment_id VARCHAR(255), -- PayU payment ID
  merchant_transaction_id VARCHAR(255) UNIQUE NOT NULL, -- Our generated ID
  
  -- Payment status
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'success', 'failed', 'cancelled')),
  
  -- Response data from PayU
  response_data JSONB,
  error_message TEXT,
  
  -- Link to allocated credits
  allocated_credit_id UUID REFERENCES employer_credits(id),
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_payment_employer_id ON payment_transactions(employer_id);
CREATE INDEX IF NOT EXISTS idx_payment_status ON payment_transactions(status);
CREATE INDEX IF NOT EXISTS idx_payment_merchant_txn_id ON payment_transactions(merchant_transaction_id);
CREATE INDEX IF NOT EXISTS idx_payment_created_at ON payment_transactions(created_at DESC);

-- Enable RLS
ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Employers can view own payment transactions"
ON payment_transactions FOR SELECT
USING (auth.uid() IN (SELECT id FROM employers WHERE id = employer_id));

CREATE POLICY "System can insert payment transactions"
ON payment_transactions FOR INSERT
WITH CHECK (true);

CREATE POLICY "System can update payment transactions"
ON payment_transactions FOR UPDATE
USING (true);

-- Add payment_transaction_id to employer_credits table
ALTER TABLE employer_credits 
ADD COLUMN IF NOT EXISTS payment_transaction_id UUID REFERENCES payment_transactions(id),
ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(20);

-- Comments
COMMENT ON TABLE payment_transactions IS 'Tracks all payment transactions through PayU gateway';
COMMENT ON COLUMN payment_transactions.amount IS 'Amount in paise (Indian Rupees * 100)';
COMMENT ON COLUMN payment_transactions.merchant_transaction_id IS 'Unique transaction ID generated by us for PayU';
