-- Additional Education Names for Educations Table
-- This script adds more education options across all levels

-- Additional 12th Standard variations (Boards and Special streams)
INSERT INTO educations (education_name, education_level) VALUES
('12th - CBSE Board', '12th'),
('12th - State Board', '12th'),
('12th - ICSE Board', '12th'),
('12th - IB (International Baccalaureate)', '12th'),
('12th - Medical Stream', '12th'),
('12th - Non-Medical Stream', '12th');

-- Additional Diploma Courses
INSERT INTO educations (education_name, education_level) VALUES
('Diploma in Web Development', 'Diploma'),
('Diploma in Digital Marketing', 'Diploma'),
('Diploma in Data Science', 'Diploma'),
('Diploma in Cyber Security', 'Diploma'),
('Diploma in Business Management', 'Diploma'),
('Diploma in Financial Accounting', 'Diploma'),
('Diploma in Hospitality Management', 'Diploma'),
('Diploma in Event Management', 'Diploma'),
('Diploma in Fashion Designing', 'Diploma'),
('Diploma in Interior Design', 'Diploma'),
('Diploma in Animation', 'Diploma'),
('Diploma in Photography', 'Diploma'),
('Diploma in Pharmacy', 'Diploma'),
('Diploma in Nursing', 'Diploma'),
('Diploma in Laboratory Technology', 'Diploma'),
('Diploma in Radiology', 'Diploma'),
('Diploma in Physiotherapy', 'Diploma');

-- Additional Graduate Degrees
INSERT INTO educations (education_name, education_level) VALUES
('B.Sc. (Computer Science)', 'Graduate'),
('B.Sc. (Information Technology)', 'Graduate'),
('B.Sc. (Mathematics)', 'Graduate'),
('B.Sc. (Physics)', 'Graduate'),
('B.Sc. (Chemistry)', 'Graduate'),
('B.Sc. (Biology)', 'Graduate'),
('B.Sc. (Biotechnology)', 'Graduate'),
('B.Sc. (Microbiology)', 'Graduate'),
('B.Sc. (Agriculture)', 'Graduate'),
('B.Sc. (Nursing)', 'Graduate'),
('B.Pharma (Bachelor of Pharmacy)', 'Graduate'),
('B.E. (Bachelor of Engineering)', 'Graduate'),
('B.Arch (Bachelor of Architecture)', 'Graduate'),
('B.Des (Bachelor of Design)', 'Graduate'),
('BFA (Bachelor of Fine Arts)', 'Graduate'),
('B.P.Ed (Bachelor of Physical Education)', 'Graduate'),
('B.Ed (Bachelor of Education)', 'Graduate'),
('BHM (Bachelor of Hotel Management)', 'Graduate'),
('BBA (Aviation)', 'Graduate'),
('BBA (International Business)', 'Graduate'),
('BCA (Data Science)', 'Graduate'),
('BCA (Cloud Computing)', 'Graduate'),
('B.Com (Accounting & Finance)', 'Graduate'),
('B.Com (Banking & Insurance)', 'Graduate'),
('B.Com (E-Commerce)', 'Graduate'),
('B.A. (Economics)', 'Graduate'),
('B.A. (Psychology)', 'Graduate'),
('B.A. (English Literature)', 'Graduate'),
('B.A. (Journalism)', 'Graduate'),
('B.A. (Mass Communication)', 'Graduate'),
('B.A. (Political Science)', 'Graduate'),
('B.A. (Sociology)', 'Graduate'),
('B.A. (History)', 'Graduate'),
('B.A. LLB (5 Year Integrated)', 'Graduate'),
('BBA LLB (5 Year Integrated)', 'Graduate'),
('BUMS (Bachelor of Unani Medicine)', 'Graduate'),
('BAMS (Bachelor of Ayurvedic Medicine)', 'Graduate'),
('BHMS (Bachelor of Homeopathic Medicine)', 'Graduate'),
('BPT (Bachelor of Physiotherapy)', 'Graduate'),
('B.Optom (Bachelor of Optometry)', 'Graduate'),
('BDS (Bachelor of Dental Surgery)', 'Graduate'),
('BVSC (Bachelor of Veterinary Science)', 'Graduate');

-- Additional Post Graduate Degrees
INSERT INTO educations (education_name, education_level) VALUES
('M.Sc. (Computer Science)', 'Post Graduate'),
('M.Sc. (Information Technology)', 'Post Graduate'),
('M.Sc. (Data Science)', 'Post Graduate'),
('M.Sc. (Artificial Intelligence)', 'Post Graduate'),
('M.Sc. (Cyber Security)', 'Post Graduate'),
('M.Sc. (Mathematics)', 'Post Graduate'),
('M.Sc. (Physics)', 'Post Graduate'),
('M.Sc. (Chemistry)', 'Post Graduate'),
('M.Sc. (Biotechnology)', 'Post Graduate'),
('M.Sc. (Microbiology)', 'Post Graduate'),
('M.Sc. (Environmental Science)', 'Post Graduate'),
('M.Sc. (Agriculture)', 'Post Graduate'),
('M.Pharma (Master of Pharmacy)', 'Post Graduate'),
('M.E. (Master of Engineering)', 'Post Graduate'),
('M.Arch (Master of Architecture)', 'Post Graduate'),
('M.Des (Master of Design)', 'Post Graduate'),
('MFA (Master of Fine Arts)', 'Post Graduate'),
('M.P.Ed (Master of Physical Education)', 'Post Graduate'),
('M.Ed (Master of Education)', 'Post Graduate'),
('MBA (Finance)', 'Post Graduate'),
('MBA (Marketing)', 'Post Graduate'),
('MBA (Human Resources)', 'Post Graduate'),
('MBA (Operations)', 'Post Graduate'),
('MBA (International Business)', 'Post Graduate'),
('MBA (Healthcare Management)', 'Post Graduate'),
('MBA (Aviation Management)', 'Post Graduate'),
('MBA (Retail Management)', 'Post Graduate'),
('MBA (Supply Chain Management)', 'Post Graduate'),
('PGDM (Post Graduate Diploma in Management)', 'Post Graduate'),
('PGDBA (Post Graduate Diploma in Business Analytics)', 'Post Graduate'),
('PGDCA (Post Graduate Diploma in Computer Applications)', 'Post Graduate'),
('MCA (Artificial Intelligence)', 'Post Graduate'),
('MCA (Cloud Computing)', 'Post Graduate'),
('MCA (Cyber Security)', 'Post Graduate'),
('M.Com (Accounting)', 'Post Graduate'),
('M.Com (Finance)', 'Post Graduate'),
('M.Com (Banking)', 'Post Graduate'),
('M.A. (Economics)', 'Post Graduate'),
('M.A. (Psychology)', 'Post Graduate'),
('M.A. (English)', 'Post Graduate'),
('M.A. (Journalism)', 'Post Graduate'),
('M.A. (Mass Communication)', 'Post Graduate'),
('M.A. (Political Science)', 'Post Graduate'),
('M.A. (Sociology)', 'Post Graduate'),
('M.A. (History)', 'Post Graduate'),
('M.A. (Public Administration)', 'Post Graduate'),
('LLM (Corporate Law)', 'Post Graduate'),
('LLM (Criminal Law)', 'Post Graduate'),
('LLM (International Law)', 'Post Graduate'),
('LLM (Intellectual Property)', 'Post Graduate'),
('MPT (Master of Physiotherapy)', 'Post Graduate'),
('MPH (Master of Public Health)', 'Post Graduate'),
('MHA (Master of Hospital Administration)', 'Post Graduate'),
('MS (Master of Surgery)', 'Post Graduate'),
('MD (Doctor of Medicine)', 'Post Graduate'),
('MDS (Master of Dental Surgery)', 'Post Graduate'),
('MVSC (Master of Veterinary Science)', 'Post Graduate');

-- Additional Doctorate Degrees
INSERT INTO educations (education_name, education_level) VALUES
('Ph.D. (Computer Science)', 'Doctorate'),
('Ph.D. (Information Technology)', 'Doctorate'),
('Ph.D. (Data Science)', 'Doctorate'),
('Ph.D. (Mathematics)', 'Doctorate'),
('Ph.D. (Physics)', 'Doctorate'),
('Ph.D. (Chemistry)', 'Doctorate'),
('Ph.D. (Biotechnology)', 'Doctorate'),
('Ph.D. (Management)', 'Doctorate'),
('Ph.D. (Commerce)', 'Doctorate'),
('Ph.D. (Economics)', 'Doctorate'),
('Ph.D. (Psychology)', 'Doctorate'),
('Ph.D. (Education)', 'Doctorate'),
('Ph.D. (Engineering)', 'Doctorate'),
('D.Litt (Doctor of Literature)', 'Doctorate'),
('D.M. (Doctorate of Medicine)', 'Doctorate'),
('M.Ch (Master of Chirurgiae - Super Specialty)', 'Doctorate'),
('DM (Doctorate in Medicine - Super Specialty)', 'Doctorate'),
('D.Pharm (Doctor of Pharmacy)', 'Doctorate');
