INSERT INTO educations (education_name, education_level) VALUES


-- Additional Diploma Programs
('Diploma Automobile', 'Diploma'),
('Diploma Textile', 'Diploma'),
('Diploma Agriculture', 'Diploma'),
('Diploma Fashion Design', 'Diploma'),
('Diploma Interior Design', 'Diploma'),
('Diploma Hotel Management', 'Diploma'),
('DMLT', 'Diploma'),
('DPT', 'Diploma'),
('DPharma', 'Diploma'),
('DNHE', 'Diploma'),

-- Additional Graduate Degrees
('B.Arch', 'Graduate'),
('B.Pharm', 'Graduate'),
('B.Ed', 'Graduate'),
('B.P.Ed', 'Graduate'),
('B.El.Ed', 'Graduate'),
('B.Lib.Sc', 'Graduate'),
('BFA', 'Graduate'),
('BHM', 'Graduate'),
('BDS', 'Graduate'),
('BAMS', 'Graduate'),
('BHMS', 'Graduate'),
('BUMS', 'Graduate'),
('BVSc', 'Graduate'),
('B.Voc', 'Graduate'),
('BPT', 'Graduate'),
('BOT', 'Graduate'),
('BMLT', 'Graduate'),
('B.Optom', 'Graduate'),
('BSW', 'Graduate'),
('BJ', 'Graduate'),
('BMM', 'Graduate'),
('BFD', 'Graduate'),

-- Additional Post Graduate Degrees
('M.Arch', 'Post Graduate'),
('M.Pharm', 'Post Graduate'),
('M.Ed', 'Post Graduate'),
('M.P.Ed', 'Post Graduate'),
('M.Lib.Sc', 'Post Graduate'),
('MFA', 'Post Graduate'),
('MHM', 'Post Graduate'),
('MDS', 'Post Graduate'),
('MS', 'Post Graduate'),
('MCh', 'Post Graduate'),
('MD Ayurveda', 'Post Graduate'),
('MD Homeopathy', 'Post Graduate'),
('MVSc', 'Post Graduate'),
('MPT', 'Post Graduate'),
('MOT', 'Post Graduate'),
('MSW', 'Post Graduate'),
('MJ', 'Post Graduate'),
('PGDM', 'Post Graduate'),
('PGDCA', 'Post Graduate'),
('PGDBA', 'Post Graduate'),
('PGD HR', 'Post Graduate'),
('PGD Marketing', 'Post Graduate'),
('PGD Finance', 'Post Graduate'),

-- Additional Doctorate Degrees
('Ph.D. CS', 'Doctorate'),
('Ph.D. Physics', 'Doctorate'),
('Ph.D. Chemistry', 'Doctorate'),
('Ph.D. Maths', 'Doctorate'),
('Ph.D. Bio', 'Doctorate'),
('Ph.D. Mgmt', 'Doctorate'),
('Ph.D. Eng', 'Doctorate'),
('DM', 'Doctorate'),
('DrPH', 'Doctorate'),
('Ed.D', 'Doctorate'),
('D.Litt', 'Doctorate');
