-- Insert pricing plans into the database
-- This script seeds the plans table with the three pricing tiers

INSERT INTO plans (
  id,
  slug,
  name,
  plan_type,
  billing_cycle,
  price,
  currency,
  credits_allocated,
  credit_validity_days,
  job_validity_days,
  applies_expiry_days,
  max_locations,
  description,
  features,
  is_active,
  created_at,
  updated_at
) VALUES
-- Classic Plan - Monthly
(
  gen_random_uuid(),
  'classic',
  'Classic',
  'classic',
  'monthly',
  999.00,
  'INR',
  5,
  30,
  30,
  30,
  5,
  'Perfect for small businesses and startups',
  '["5 Job Postings", "Job validity: 30 days", "Applicants valid for: 30 days", "Up to 5 job locations", "Email support"]'::jsonb,
  true,
  now(),
  now()
),
-- Classic Plan - Yearly
(
  gen_random_uuid(),
  'classic',
  'Classic',
  'classic',
  'yearly',
  9999.00,
  'INR',
  60,
  365,
  365,
  365,
  5,
  'Perfect for small businesses and startups',
  '["60 Job Postings", "Job validity: 365 days", "Applicants valid for: 365 days", "Up to 5 job locations", "Email support", "Save 17% compared to monthly"]'::jsonb,
  true,
  now(),
  now()
),
-- Premium Plan - Monthly
(
  gen_random_uuid(),
  'premium',
  'Premium',
  'premium',
  'monthly',
  2499.00,
  'INR',
  15,
  30,
  60,
  60,
  10,
  'Best for growing companies with regular hiring needs',
  '["15 Job Postings", "Job validity: 60 days", "Applicants valid for: 60 days", "Up to 10 job locations", "Priority support", "Advanced analytics", "Custom screening questions"]'::jsonb,
  true,
  now(),
  now()
),
-- Premium Plan - Yearly
(
  gen_random_uuid(),
  'premium',
  'Premium',
  'premium',
  'yearly',
  24999.00,
  'INR',
  180,
  365,
  60,
  60,
  10,
  'Best for growing companies with regular hiring needs',
  '["180 Job Postings", "Job validity: 60 days", "Applicants valid for: 60 days", "Up to 10 job locations", "Priority support", "Advanced analytics", "Custom screening questions", "Save 17% compared to monthly"]'::jsonb,
  true,
  now(),
  now()
),
-- Enterprise Plan - Monthly
(
  gen_random_uuid(),
  'enterprise',
  'Enterprise',
  'enterprise',
  'monthly',
  4999.00,
  'INR',
  30,
  30,
  90,
  90,
  999,
  'For large organizations with high-volume recruitment',
  '["30 Job Postings", "Job validity: 90 days", "Applicants valid for: 90 days", "Unlimited job locations", "Dedicated account manager", "Premium support 24/7", "Advanced analytics & reporting", "Custom integrations", "Bulk job posting"]'::jsonb,
  true,
  now(),
  now()
),
-- Enterprise Plan - Yearly
(
  gen_random_uuid(),
  'enterprise',
  'Enterprise',
  'enterprise',
  'yearly',
  49999.00,
  'INR',
  360,
  365,
  90,
  90,
  999,
  'For large organizations with high-volume recruitment',
  '["360 Job Postings", "Job validity: 90 days", "Applicants valid for: 90 days", "Unlimited job locations", "Dedicated account manager", "Premium support 24/7", "Advanced analytics & reporting", "Custom integrations", "Bulk job posting", "Save 17% compared to monthly"]'::jsonb,
  true,
  now(),
  now()
);
